works:
- {
  title: 'Evalueserve',
  subtitle: 'Research, Design, and Consulting',
  folder: 'evs',
  file: 'works/evs.html'
}
- {
  title: 'Carolina Digital Repository',
  subtitle: 'The Two-Year Journey of a Digital Migration',
  folder: 'cdr',
  file: 'works/cdr.html'
}
- {
  title: 'nVisium',
  subtitle: 'Designing for Application Security',
  folder: 'nv',
  file: 'works/nv.html'
}
- {
  title: 'Munis Delivery App',
  subtitle: 'My First User Experience Role',
  folder: 'tyler',
  file: 'works/tyler.html'
}
- {
  title: 'Advanced Structure and Composites Center',
  subtitle: 'A Rebranding Campaign Led by Students',
  folder: 'ascc',
  file: 'works/ascc.html'
}

socials:
- {
  icon: 'linkedin',
  link: 'https://www.linkedin.com/in/hydong'
}
- {
  icon: 'reddit',
  link: 'https://www.reddit.com/user/YidonHongski'
}
- {
  icon: 'github',
  link: 'https://github.com/scorchingoyster'
}
- {
  icon: 'blog',
  link: 'https://hirc.substack.com/'
}
