works:
- {
  title: 'Evalueserve',
  subtitle: 'Researcher, Designer, and Consultant',
  folder: 'evs',
  file: 'works/evs.html'
}
- {
  title: 'Carolina Digital Repository',
  subtitle: 'The Two-Year Journey of a Digital Migration',
  folder: 'cdr',
  file: 'works/cdr.html'
}

socials:
- {
  icon: 'linkedin',
  link: 'https://www.linkedin.com/in/hydong'
}
- {
  icon: 'reddit',
  link: 'https://www.reddit.com/user/YidonHongski'
}
- {
  icon: 'github',
  link: 'https://github.com/scorchingoyster'
}
- {
  icon: 'blog',
  link: 'https://hirc.substack.com/'
}
